# Generated by Django 3.2.6 on 2021-08-30 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 16, 36, 11, 846261, tzinfo=utc), verbose_name='Дата получения заказа'),
        ),
    ]
