# Generated by Django 3.2.6 on 2021-08-30 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 17, 25, 52, 841048, tzinfo=utc), verbose_name='Дата получения заказа'),
        ),
    ]
